In [11]:
import os
import numpy as np
import tensorflow as tf
import pandas as pd

In [2]:
np.expand_dims

<function expand_dims at 0x0000027074584EB0>

In [12]:
df=pd.read_csv('C:/Users/VINUTHA R/Downloads/jigsaw-toxic-comment-classification-challenge/train_csv/train.csv')

In [4]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [5]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [13]:
df.iloc[1]['comment_text']

"D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)"

tokenization

In [14]:
from tensorflow import keras
from keras.layers import TextVectorization

In [8]:
TextVectorization??

Init signature:
TextVectorization(
    max_tokens=None,
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    ngrams=None,
    output_mode='int',
    output_sequence_length=None,
    pad_to_max_tokens=False,
    vocabulary=None,
    idf_weights=None,
    sparse=False,
    ragged=False,
    encoding='utf-8',
    **kwargs,
)
Source:        
@keras_export(
    "keras.layers.TextVectorization",
    "keras.layers.experimental.preprocessing.TextVectorization",
    v1=[],
)
class TextVectorization(base_preprocessing_layer.PreprocessingLayer):
    """A preprocessing layer which maps text features to integer sequences.

    This layer has basic options for managing text in a Keras model. It
    transforms a batch of strings (one example = one string) into either a list
    of token indices (one example = 1D tensor of integer token indices) or a
    dense representation (one example = 1D tensor of float values representing
    data about the example's tokens). This layer is 

In [15]:
X=df['comment_text']
y=df[df.columns[2:]].values

In [10]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [16]:
MAX_WORDS = 200000

In [17]:
vectorizer = TextVectorization(max_tokens=MAX_WORDS,output_sequence_length=1800,output_mode='int')

In [13]:
type(X)

pandas.core.series.Series

In [18]:
vectorizer.adapt(X.values)

In [15]:
vectorizer("Hello world")[:2]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([288, 263], dtype=int64)>

In [16]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [17]:
vectorized_text = vectorizer(X.values)

In [18]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [19]:
len(X)

159571

In [20]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset=dataset.batch(16)
dataset=dataset.prefetch(8) 

In [21]:
for element in dataset.take(5):
    vectorized_text, y = element
    print("Vectorized Text:", vectorized_text)
    print("Labels:", y)
    print("\n")

Vectorized Text: tf.Tensor(
[[   451 128852  62242 ...      0      0      0]
 [ 64863   2116    979 ...      0      0      0]
 [  1456   8141      8 ...      0      0      0]
 ...
 [  1215    384     14 ...      0      0      0]
 [ 15900  50181    171 ...      0      0      0]
 [    11    693  63671 ...      0      0      0]], shape=(16, 1800), dtype=int64)
Labels: tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]], shape=(16, 6), dtype=int64)


Vectorized Text: tf.Tensor(
[[  636     8    55 ...     0     0     0]
 [    1   124     7 ...     0     0     0]
 [    8    69    21 ...     0     0     0]
 ...
 [50690  1243   278 ...     0     0     0]
 [  718 19067    46 ...     0     0     0]
 [ 2541     9  2130 ...     0     0     0]], shape=(16, 1800), dtype=int64)
Labels: tf.Tensor(
[[0 0 

In [22]:
batch_x,batch_y=dataset.as_numpy_iterator().next()

In [23]:
batch_x.shape

(16, 1800)

In [24]:
train = dataset.take(int(len(dataset)* 0.7))
val = dataset.skip(int(len(dataset)* 0.7)).take(int(len(dataset)* 0.2))
test = dataset.skip(int(len(dataset)* 0.9)).take(int(len(dataset)* 0.1))

In [25]:
train_generator = train.as_numpy_iterator().next()

In [26]:
from keras.layers import LSTM,Dropout,Bidirectional,Dense,Embedding
from keras.models import Sequential

The analysis of sequential data such as text sentences, time-series, and other discrete sequence data prompted the development of Sequence Models. These models are better suited to handle sequential data, whereas Convolutional Neural Networks are better suited to treat spatial data.

The crucial element to remember about sequence models is that the data we’re working with are no longer independently and identically distributed (i.i.d.) samples, and the data are reliant on one another due to their sequential order. For speech recognition, voice recognition, time series prediction, and natural language processing, sequence models are particularly popular.

Sequential model: RNN for time series data
Many-to-one

This is used to categorize emotions. A succession of words or even paragraphs of words is anticipated as input. The result can be a continuous-valued regression output that represents the likelihood of having a favourable attitude.
The name recurrent comes from the fact that it receives two inputs, one from the user and the other from the previous output (output goes as input).

LSTM:
In a cell of the LSTM neural network, the first step is to decide whether we should keep the information from the previous time step or forget it. Here is the equation for forget gate.
The input gate is used to quantify the importance of the new information carried by the input. Here is the equation of the input gate
New informations:
Nt = tanh(xt * Uc + H(t-1)*Wc)
if Nt<0 the info is subtracted from the cell state and if the value is positive, the information is added to the cell state at the current timestamp.



Hidden Layers:
Rectified Linear Unit (ReLU) is a popular choice for activation functions in hidden layers due to its simplicity and efficiency in training deep networks.

In [27]:
model = Sequential()
# Create a embedding layer
model.add(Embedding(MAX_WORDS+1,32))
# 32 different units
# tanh - GPU acceleratiosn required by LSTM
model.add(Bidirectional(LSTM(32,activation='tanh')))
# FEATURE extractors Full connected layers
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
# Final layer
# 6 units in our output y[0] = [0,0,0,0,0,0]
model.add(Dense(6,activation='sigmoid'))


In [28]:
model.compile(loss='BinaryCrossentropy',optimizer='Adam')


In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirection  (None, 64)                16640     
 al)                                                             
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [30]:
tf.config.list_physical_devices('GPU')

[]

In [31]:
#history = model.fit(train,epochs=1,validation_data=val)

In [32]:

# Assuming 'model' is your Sequential model
#model.save('C:///Desktop/sunitha/4th_sem/my_model.h5')


In [33]:
#save_path = r'C:/Users/VINUTHA R/Desktop/Sunitha/4th sem/my_model.h5'
#model.save(save_path)

In [2]:
from keras.models import Sequential,load_model
loaded_model = load_model(r'C:/Users/VINUTHA R/Desktop/Sunitha/4th sem/my_model.h5')

In [35]:
print(loaded_model.history)

None


In [36]:
loss = loaded_model.evaluate(val)

1994/1994 [==============================] - 250s 119ms/step - loss: 0.0446


In [37]:
print(loss)

0.04463207721710205


In [38]:
predictions = loaded_model.predict(test)

997/997 [==============================] - 137s 120ms/step


Before predicting we need to tokenize

In [39]:
input_text = vectorizer("You're amazing")
input_text1 = vectorizer("I'll kill you")

In [40]:
batch_X,batch_y = test.as_numpy_iterator().next()

In [41]:
(loaded_model.predict(batch_X) > 0.5).astype(int)


1/1 [==============================] - 5s 5s/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0]])

In [42]:
(loaded_model.predict(batch_y) > 0.5).astype(int)

1/1 [==============================] - 6s 6s/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [43]:
from keras.metrics import Precision,Recall,CategoricalAccuracy


In [44]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [45]:
for batch in test.as_numpy_iterator():
    X_true,y_true = batch
    yhat = model.predict(X_true)
    y_true= y_true.flatten()
    yhat=yhat.flatten()
    pre.update_state(y_true,yhat)
    re.update_state(y_true,yhat)
    acc.update_state(y_true,yhat)
    




1/1 [==============================] - 6s 6s/step


In [46]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()},Accuracy:{acc.result().numpy()}')

Precision: 0.021433185786008835, Recall:0.21843686699867249,Accuracy:0.0


In [47]:
%pip install gradio jinja2


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 0.0/50.5 kB ? eta -:--:--
     -------- ------------------------------- 10.2/50.5 kB ? eta -:--:--
     ------------------------------ ------- 41.0/50.5 kB 388.9 kB/s eta 0:00:01
     -------------------------------------- 50.5/50.5 kB 365.8 kB/s eta 0:00:00
     ---------------------------------------- 0.0/65.6 kB ? eta -:--:--
     ------------------ --------------------- 30.7/65.6 kB ? eta -:--:--
     -------------------------------------- 65.6/65.6 kB 878.7 kB/s eta 0:00:00
     ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
     ---------------------------------------- 45.7/45.7 kB 2.2 MB/s eta 0:00:00
     ---------------------------------------- 0.0/45.9 kB ? eta -:--:--
     ---------------------------------------- 45.9/45.9 kB ? eta 0:00:00
     ---------------------------------------- 0.0/124.7 kB ? eta -:--:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.16.0 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.


In [1]:
%pip install --upgrade typing-extensions

import gradio as gr

In [19]:
def store_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = loaded_model.predict(vectorized_comment)
    text=''
    for idx,col in enumerate(df.columns[2:]):
        text += '{}:{}\n'.format(col,results[0][idx] > 0.5)
    return text
    

In [23]:
interface = gr.Interface(fn=store_comment,inputs = gr.Textbox(lines=2,placeholder='Comment to score'),outputs='text')

In [24]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.


1/1 [==============================] - 0s 346ms/step
